worker_processes auto;
pid /tmp/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout;
  error_log /dev/stderr warn;
  sendfile on;
  tcp_nopush on;
  keepalive_timeout 65;

  server {
    listen 8080;
    server_name _;
    root /app/site;

    location / {
      try_files $uri $uri/ /index.html;
    }

    location /runtime/ {
      try_files $uri =404;
      add_header Accept-Ranges bytes always;
      add_header Cache-Control "no-cache" always;
    }
  }
}
